### ISSUE TITLE
Improve bundle-sizes and loading times

### ISSUE THREAD

**Issue by voliva** [polkadot-api/polkadot-api#426]
## Introduction

Currently the codegen generates the descriptor files with the following structure. Each box is a file and each arrow is an import between files, denoting what does it import from each file. A dashed arrow means a dynamic import.

![image](https://github.com/polkadot-api/polkadot-api/assets/5365487/81e05d34-c53f-4bfb-9bf7-72c00c437599)
 
Each chain file has the descriptors for their chain, which essentially has all the information for that chain: Every runtime api and their methods, every pallet and their storage queries, transaction calls, constant names, event names, etc. and for each one of these, an index. The index specifies which checksum that particular entry has, which will be needed to check for compatibility.

Common types is a file that has every single type referenced by those chains, which lets them get reused across different ones. Some of these types are enums from the well-known types registry, so they are exported with a name from the index file.

And lastly, the checksum file is just an array with every checksum referenced from the chain files. This file is already lazy loaded, so that it doesn't impact the main chunk when bundling a dApp, which was needed because checksums are hard to compress.

However, the descriptor files take a considerable amount of bundle size, specially when dealing with multiple chains. These descriptors are currently represented as a nested object with every path for that chain, and that adds up into a data structure that the bundler can't optimize.

The following image shows the bundle size for a simple React dApp that loads the balance of an account, with parsed size (not compressed). The checksum chunk, marked in blue, is already taken out. But the descriptor file, marked in red, is still in the main bundle.

![image](https://github.com/polkadot-api/polkadot-api/assets/5365487/3580ef5c-5d7b-450f-a856-92ddab71775b)

In this case it's still smaller than React, but it doesn't scale as we keep adding more chains. The bundle visualizer for the [react-teleport example](https://github.com/polkadot-api/react-teleport-example) looks like this:

![image](https://github.com/polkadot-api/polkadot-api/assets/5365487/f6389c87-df5d-42ab-bada-3ce7053268d9)

 ## Proposal

We want to optimize this in a similar fashion to what we did with checksums, by having the main descriptor files contain very little runtime information, to let bundlers optimize the size, while still keeping the type information to not effect the developer experience.

A possible new generated descriptors file structure could look like this:

![image](https://github.com/polkadot-api/polkadot-api/assets/5365487/7733fd97-57f0-4be8-bf1b-636ae4630c2c)

The idea is that during codegen, we can analyze all the names referenced by every chain, and use this information to structure the data in a way that we can minimize the amount of data on the main chunk (so each chain file would mainly have Type definitions and a very little amount of runtime code), and move the descriptor information in a separate file that can find and remove duplicate references while still being compact.

For instance, on the chain files we might use a [Proxy object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to read the pallet name + storage query that the developer is using, then wait for the descriptor file to finish loading (as now it's being loaded in the background) before we can look up which checksum does it refer to.

This way, the bundler will see that all the chain file exports on runtime is one single proxy*, while the IDE would still load in all the type information that the chain file, which should keep the developer experience intact. *: this is all tentative, it might change as we get to work on it

This Proxy method we are already using it on known enum types for the same reason: The bundler just exports a `new Proxy()` for all of the enums, and this Proxy builds the `{ type: string, value: unknown }` object when the developer calls e.g. `XcmV3Junction.AccountId32(account)`

Another optimization we have in mind is to let the developer whitelist which parts of the metadata they want to keep, removing the rest of them. But to not effect the developer experience, where we want to have everything available while we're developing, the codegen would have two build modes: an opt-in mode where it would use the metadata, and the default where it would generate everything.

The idea is that we could have a small type utility which would let the developer pick in a very granular way, a small proof-of-concept shown here:

https://github.com/polkadot-api/polkadot-api/assets/5365487/f4901e3e-62fb-42d1-a192-1273eab4839b

This could be extended in a future proposal to automate this based on code analysis.

## Tasks

- [x] Separate types from descriptors for chain files
- [x] Lazy load descriptors
- [x] Deduplicate common descriptors
- [x] Optimize descriptor data structure for bundle size
- [x] Add whitelist to codegen
- [x] Expose whitelist through CLI
