### ISSUE TITLE
Tx improvements

### ISSUE THREAD

**Issue by josepot** [polkadot-api/polkadot-api#497]
## Tasks

- [x] Allow entering a custom nonce.
- [x] Keep on validating transactions after they have been broadcasted
- [x] Make `bestChainBlockIncluded` event payload consistent with the payload of the `finalized` event.
- [x] Emit `noLongerInBestBlock` event
- [x] Make it easier to access the extrinsic hash

**Comment by josepot** [comment]
I propose refinements to the `TxEvent` type to offer a more detailed tracking of transaction states through their lifecycle. Here’s the enhanced type structure in TypeScript:

```ts
export type TxEvent =
  | TxSigned
  | TxBroadcasted
  | TxBestBlocksState
  | TxFinalized;

type TxSigned = { type: "signed"; txHash: HexString; tx: Binary };

type TxBroadcasted = { type: "broadcasted"; txHash: HexString };

type TxBestBlocksState = {
  type: "stateInBestBlocks";
  txHash: HexString;
  state: TxInBestBlocksValid | TxInBestBlocksInvalid | TxInBestBlocksIncluded;
};

type TxInBestBlocksValid = { type: "valid" };

type TxInBestBlocksInvalid = { type: "invalid" };

type TxInBestBlocksIncluded = {
  type: "included"
} & TxEventsPayload;

type TxEventsPayload = {
  ok: boolean;
  events: Array<SystemEvent>;
  block: { hash: string; index: number };
};

type TxFinalized = {
  type: "finalized";
  txHash: HexString;
} & TxEventsPayload;
```

### Detailed Explanation

- **`signed`**: This event indicates that the transaction has been signed. The `tx` field contains the binary representation of the transaction, and `txHash` provides the hash of the transaction.
  
- **`broadcasted`**: This event signifies that the transaction has passed initial validations against the current finalized block and has been broadcasted to the network.

- **`stateInBestBlocks`**: Represents the ongoing status of the transaction as it relates to the best blocks:
  - **`valid`**: The transaction is deemed valid within the current best block, typically following a successful `broadcasted` event.
  - **`invalid`**: The transaction has failed validation against one of the blocks that are contenders for becoming the finalized block. This status may lead to an error if the block becomes finalized.
  - **`included`**: The transaction has been included in one of the interim blocks. This status provides additional details like transaction success or failure, the specific block, and event data.
  
  This event type is particularly useful for users who need to track detailed states of a transaction through the block validation process. It's worth pointing out that many users may want to ignore this event, and/or to treat the `valid`/`invalid` event as a "tx-not-in-best-blocks" event.

- **`finalized`**: This terminal event is triggered once the transaction is included in a finalized block, effectively completing its lifecycle. It includes all the payload data from the `included` state, offering a comprehensive view of the transaction's outcome.

The proposed structure aims to provide a transparent, comprehensive view of transaction states, improving monitoring capabilities and developer interactions.

I welcome any feedback or questions to refine this further. Thank you! 🙏
